version: '3.4'

services:
  configserver:
    image: ostock/configserver:0.0.1-SNAPSHOT
    ports:
      - "8071:8071"
    environment:
      SPRING_PROFILES_ACTIVE: "dev"
    networks:
      backend:
        aliases:
          - "configserver"
networks:
  backend:
    driver: bridge

